<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter">
	<h2 class="title text-center"><?php echo __('Sign-up for Special Offers, News & More'); ?></h2>
    <div class="content center-block newsletter-full">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field form-group newsletter">
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Email Address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
	                <button class="action subscribe btn btn-default btn-sm" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
	                    <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
	                </button>                                
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "js/newsletter_subscriber_ajax": { }
        }
    }
</script>