<?php
/**
 * Mageinn_Hint extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Mageinn
 * @package     Mageinn_Hint
 * @copyright   Copyright (c) 2017 Mageinn. (http://mageinn.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \Magento\Swatches\Block\LayeredNavigation\RenderLayered $block
 * @var \Mageinn\Hint\Helper\Data $helper
 */

$helper = $this->helper('Mageinn\Hint\Helper\Data');
$swatchData = $block->getSwatchData();
?>

<div class="swatch-attribute swatch-layered test <?= $swatchData['attribute_code'] ?>"
     attribute-code="<?= $swatchData['attribute_code'] ?>"
     attribute-id="<?= $swatchData['attribute_id'] ?>"
>
    <div class="swatch-attribute-options clearfix">
        <?php foreach ($swatchData['options'] as $option => $label) : ?>
            <a href="<?= $label['link'] ?>"
               aria-label="<?= $label['label'] ?>"
               class="swatch-option-link-layered"
            >
                <?php if (isset($swatchData['swatches'][$option]['type'])) :
                    $swatchValue = $swatchData['swatches'][$option]['value'];
                    $hint = htmlspecialchars($helper->getOptionHint($option, $swatchData['attribute_id']), ENT_QUOTES);
                    $customClass = $label['custom_style'];

                    $optionClass = '';
                    $optionType = 0;
                    $optionTooltipThumb = '';
                    $optionTooltipValue = '';
                    $optionStyle = '';
                    $optionContent = '';
                    switch ($swatchData['swatches'][$option]['type']) {
                        case '3':
                            $optionType = 3;
                            break;
                        case '2':
                            $optionClass = 'image';
                            $optionType = 2;
                            $optionTooltipThumb = $block->getSwatchPath('swatch_thumb', $swatchValue);
                            $optionStyle = sprintf(
                                'background: url(%s) no-repeat center; background-size: initial;',
                                $block->getSwatchPath('swatch_image', $swatchValue)
                            );
                            break;
                        case '1':
                            $optionClass = 'color';
                            $optionType = 1;
                            $optionTooltipValue = $swatchValue;
                            $optionStyle = sprintf(
                                'background: %s no-repeat center; background-size: initial;',
                                $swatchValue
                            );
                            break;
                        case '0':
                        default:
                            $optionClass = 'text';
                            $optionType = 0;
                            $optionContent = $swatchValue;
                    }
                    ?>

                    <div class="swatch-option <?= $optionClass ?> <?= $customClass ?>"
                         tabindex="-1"
                         option-type="<?= $optionType ?>"
                         option-id="<?= $option ?>"
                         option-label="<?= $label['label'] ?>"
                         option-tooltip-thumb="<?= $optionTooltipThumb ?>"
                         option-tooltip-value="<?= $optionTooltipValue ?>"
                         option-tooltip-hint="<?= $hint ?>"
                         <?= empty($optionStyle) ? '' : sprintf(' style="%s"', $optionStyle) ?>
                    ><?= $optionContent ?></div>
                <?php endif ?>
            </a>
        <?php endforeach; ?>
    </div>
</div>

<script>
    require(["jquery", "jquery/ui", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('.swatch-layered.<?= $swatchData['attribute_code'] ?>')
            .find('[option-type="1"], [option-type="2"], [option-type="0"], [option-type="3"]')
            .SwatchRendererTooltip();
    });
</script>
