<?php
/**
 * Mageinn_Hint extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Mageinn
 * @package     Mageinn_Hint
 * @copyright   Copyright (c) 2017 Mageinn. (http://mageinn.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \Magento\ConfigurableProduct\Block\Product\View\Type\Configurable $block
 * @var \Mageinn\Hint\Helper\Data $helper
 * @var \Magento\ConfigurableProduct\Model\Product\Type\Configurable\Attribute[] $_attributes
 */
$_product    = $block->getProduct();
$_attributes = $block->decorateArray($block->getAllowAttributes());
$helper = $this->helper('Mageinn\Hint\Helper\Data');

if (empty($_attributes)) {
    return;
}
if (! $_product->isSaleable()) {
    return;
}
?>

<?php foreach ($_attributes as $_attribute) : ?>
    <div class="field configurable required">
        <label class="label" for="attribute<?= $_attribute->getAttributeId() ?>">
            <span><?= $block->escapeHtml($_attribute->getProductAttribute()->getStoreLabel()) ?></span>
        </label>
        <span>
            <?= $helper->getTitleHintHtml($_attribute->getAttributeId()); ?>
        </span>
        <div class="control">
            <select name="super_attribute[<?= $_attribute->getAttributeId() ?>]"
                    data-selector="super_attribute[<?= $_attribute->getAttributeId() ?>]"
                    data-validate="{required:true}"
                    id="attribute<?= $_attribute->getAttributeId() ?>"
                    class="super-attribute-select">
                <option value=""><?= __('Choose an Option...') ?></option>
            </select>
        </div>
    </div>
<?php endforeach; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "configurable": {
                "spConfig": <?= $block->getJsonConfig() ?>,
                "onlyMainImg": <?= $block->getVar('change_only_base_image', 'Magento_ConfigurableProduct') ? 'true' : 'false' ?>
            }
        }
    }
</script>
