<?php
/**
 * Mageinn_Hint extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Mageinn
 * @package     Mageinn_Hint
 * @copyright   Copyright (c) 2017 Mageinn. (http://mageinn.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \Magento\Swatches\Block\Product\Renderer\Configurable $block
 * @var \Mageinn\Hint\Helper\Data $helper
 */

$_product    = $block->getProduct();
$_attributes = $block->decorateArray($block->getAllowAttributes());
$helper = $this->helper('Mageinn\Hint\Helper\Data');
?>

<div class="swatch-opt" data-role="swatch-options"></div>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "jsonConfig": <?= $block->getJsonConfig() ?>,
                "jsonSwatchConfig": <?= $block->getJsonSwatchConfig() ?>,
                "mediaCallback": "<?= $block->getMediaCallback() ?>",
                "gallerySwitchStrategy": "<?= $block->getVar(
                    'gallery_switch_strategy',
                    'Magento_ConfigurableProduct'
                ) ?: 'replace' ?>",
                "jsonSwatchImageSizeConfig": <?= $block->getJsonSwatchSizeConfig() ?>
            }
        },
        "*" : {
            "Magento_Swatches/js/catalog-add-to-cart": {}
        }
    }
</script>
