<?php
/**
 * Mageinn_Hint extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Mageinn
 * @package     Mageinn_Hint
 * @copyright   Copyright (c) 2017 Mageinn. (http://mageinn.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \Magento\Catalog\Block\Product\View\Options\Type\Date $block
 * @var \Mageinn\Hint\Helper\Data $helper
 */

use Magento\Catalog\Api\Data\ProductCustomOptionInterface;

$helper = $this->helper('Mageinn\Hint\Helper\Data');
$_option = $block->getOption();
$_optionId = $_option->getId();
$class = $_option->getIsRequire() ? ' required' : '';
$typeDateTimeOrDate = in_array(
    $_option->getType(),
    [ProductCustomOptionInterface::OPTION_TYPE_DATE_TIME, ProductCustomOptionInterface::OPTION_TYPE_DATE]
);
$typeDateTimeOrTime = in_array(
    $_option->getType(),
    [ProductCustomOptionInterface::OPTION_TYPE_DATE_TIME, ProductCustomOptionInterface::OPTION_TYPE_TIME]
);
?>

<div class="field date<?= $class ?>"
    data-mage-init='{"priceOptionDate":{"fromSelector":"#product_addtocart_form"}}'>
    <fieldset class="fieldset fieldset-product-options-inner<?= $class ?>">
        <legend class="legend">
            <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
            <?= $block->getFormatedPrice() ?>
            <span>
                <?= $helper->getCustomOptionHtml($_option->getHint()) ?>
            </span>
        </legend>
        <div class="control">
            <?php if ($typeDateTimeOrDate) : ?>
                <?= $block->getDateHtml() ?>
            <?php endif; ?>
            <?php if ($typeDateTimeOrTime) : ?>
                <?= $block->getTimeHtml() ?>
            <?php endif; ?>
            <?php $validateType = $_option->getIsRequire() ? 'validate-required-datetime' : 'validate-optional-datetime'; ?>
            <input type="hidden"
                   name="validate_datetime_<?= $_optionId ?>"
                   class="validate-datetime-<?= $_optionId ?>"
                   value=""
                   data-validate="{'<?= $validateType ?>':<?= $_optionId?>}"
            />
            <script type="text/x-magento-init">
                {
                    "#product_addtocart_form": {
                        "validation": {
                            "ignore": ":hidden:not(input[name^='validate_datetime_'])"
                        }
                    }
                }
            </script>
        </div>
    </fieldset>
</div>
