<?php
/**
 * Mageinn_Hint extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Mageinn
 * @package     Mageinn_Hint
 * @copyright   Copyright (c) 2017 Mageinn. (http://mageinn.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \Magento\Catalog\Block\Product\View\Options\Type\File $block
 * @var \Mageinn\Hint\Helper\Data $helper
 */

$_option = $block->getOption();
/** @var \Magento\Framework\DataObject $_fileInfo */
$_fileInfo = $block->getFileInfo();
$_fileExists = $_fileInfo->hasData();
$_fileName = 'options_' . $_option->getId() . '_file';
$_fieldNameAction = $_fileName . '_action';
$_fieldValueAction = $_fileExists ? 'save_old' : 'save_new';
$_fileNamed = $_fileName . '_name';
$class = $_option->getIsRequire() ? ' required' : '';
$helper = $this->helper('Mageinn\Hint\Helper\Data');
?>
<div class="field file<?= $class ?>">
    <label class="label" for="<?= $_fileName ?>" id="<?= $_fileName ?>-label">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
        <?= $block->getFormatedPrice() ?>
    </label>
    <span>
        <?= $helper->getCustomOptionHtml($_option->getHint()) ?>
    </span>
    <?php if ($_fileExists) : ?>
        <div class="control">
            <span class="<?= $_fileNamed ?>"><?= $block->escapeHtml($_fileInfo->getTitle()) ?></span>
            <a href="javascript:void(0)" class="label" id="change-<?= $_fileName ?>" >
                <?= __('Change') ?>
            </a>
            <?php if (! $_option->getIsRequire()) : ?>
                <input type="checkbox" id="delete-<?= $_fileName ?>" />
                <span class="label"><?= __('Delete') ?></span>
            <?php endif ?>
        </div>
    <?php endif ?>
    <div class="control" id="input-box-<?= $_fileName ?>"
             data-mage-init='{"priceOptionFile":{
                "fileName":"<?= $_fileName ?>",
                "fileNamed":"<?= $_fileNamed ?>",
                "fieldNameAction":"<?= $_fieldNameAction ?>",
                "changeFileSelector":"#change-<?= $_fileName ?>",
                "deleteFileSelector":"#delete-<?= $_fileName ?>"}
             }'
            <?= $_fileExists ? ' style="display:none"' : '' ?>
    >
        <input type="file"
               name="<?= $_fileName ?>"
               id="<?= $_fileName ?>"
               class="product-custom-option<?= $class ?>"
                <?= $_fileExists ? ' disabled="disabled"' : '' ?>
        />
        <input type="hidden" name="<?= $_fieldNameAction ?>" value="<?= $_fieldValueAction ?>" />
        <?php if ($_option->getFileExtension()) : ?>
            <p class="note">
                <?= __('Compatible file extensions to upload')?>: <strong><?= $_option->getFileExtension() ?></strong>
            </p>
        <?php endif; ?>
        <?php if ($_option->getImageSizeX() > 0) : ?>
            <p class="note">
                <?= __('Maximum image width')?>: <strong><?= $_option->getImageSizeX() ?> <?= __('px.')?></strong>
            </p>
        <?php endif; ?>
        <?php if ($_option->getImageSizeY() > 0) : ?>
            <p class="note">
                <?= __('Maximum image height')?>: <strong><?= $_option->getImageSizeY() ?> <?= __('px.')?></strong>
            </p>
        <?php endif ?>
    </div>
</div>
