<?php
/**
 * Mageinn_Hint extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Mageinn
 * @package     Mageinn_Hint
 * @copyright   Copyright (c) 2017 Mageinn. (http://mageinn.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \Mageinn\Hint\Block\Product\View\Options\Type\Select\Select $block
 * @var \Mageinn\Hint\Helper\Data $helper
 */

use Magento\Catalog\Api\Data\ProductCustomOptionInterface;

$_option = $block->getOption();
$class = $_option->getIsRequire() ? ' required' : '';
$helper = $this->helper('Mageinn\Hint\Helper\Data');
$typeRadioOrCheckbox = in_array(
    $_option->getType(),
    [ProductCustomOptionInterface::OPTION_TYPE_RADIO, ProductCustomOptionInterface::OPTION_TYPE_CHECKBOX]
);
?>

<div class="field<?= $class ?>">
    <label class="label" for="select_<?= $_option->getId() ?>">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <span>
        <?= $helper->getCustomOptionHtml($_option->getHint()) ?>
    </span>
    <div class="control">
        <?= $block->getValuesHtml() ?>
        <?php if ($_option->getIsRequire() && $typeRadioOrCheckbox) : ?>
            <span id="options-<?= $_option->getId() ?>-container"></span>
        <?php endif ?>
    </div>
</div>
