<?php
/**
 * Mageinn_Hint extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Mageinn
 * @package     Mageinn_Hint
 * @copyright   Copyright (c) 2017 Mageinn. (http://mageinn.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \Magento\LayeredNavigation\Block\Navigation\FilterRenderer $block
 * @var \Mageinn\Hint\Helper\Data $helper
 * @var \Magento\Catalog\Helper\Data $catalogHelper
 * @var \Magento\Catalog\Model\Layer\Filter\Item[] $filterItems
 * @see \Magento\LayeredNavigation\Block\Navigation\FilterRenderer::render()
 */
$helper = $this->helper('Mageinn\Hint\Helper\Data');
$catalogHelper = $this->helper('Magento\Catalog\Helper\Data');
?>
<ol class="items">
    <?php foreach ($filterItems as $filterItem) : ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0) : ?>
                <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>">
                    <?= $filterItem->getLabel() ?>
                    <?php if ($catalogHelper->shouldDisplayProductCountOnLayer()) : ?>
                        <span class="count">
                            <?= $filterItem->getCount()?>
                            <span class="filter-count-label">
                                <?= $filterItem->getCount() == 1 ? __('item') : __('items') ?>
                            </span>
                        </span>
                    <?php endif; ?>
                </a>
                <?php if ($filterItem->getFilter()->getData('attribute_model')) : ?>
                    <?= $helper->getOptionHintHtml($filterItem->getValue(), $filterItem->getFilter()->getAttributeModel()->getAttributeId()); ?>
                <?php endif; ?>
            <?php else :?>
                <?= $filterItem->getLabel() ?>
                <?php if ($catalogHelper->shouldDisplayProductCountOnLayer()) : ?>
                    <span class="count">
                        <?= $filterItem->getCount()?>
                        <span class="filter-count-label">
                            <?= $filterItem->getCount() == 1 ? __('item') : __('items') ?>
                        </span>
                    </span>
                <?php endif; ?>
                <?= $helper->getOptionHintHtml($filterItem->getValue(), $filterItem->getFilter()->getAttributeModel()->getAttributeId()); ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
