<?php
/**
 * Mageinn_Hint extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Mageinn
 * @package     Mageinn_Hint
 * @copyright   Copyright (c) 2017 Mageinn. (http://mageinn.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \Magento\LayeredNavigation\Block\Navigation $block
 * @var \Mageinn\Hint\Helper\Data $helper
 */
if (! $block->canShowBlock()) {
    return;
}
$helper = $this->helper('Mageinn\Hint\Helper\Data');
?>

<div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
    <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
    <div class="block-title filter-title" data-count="<?= $filtered ?>">
        <strong data-role="title"><?= __('Shop By') ?></strong>
    </div>
    <div class="block-content filter-content">
        <?= $block->getChildHtml('state') ?>

        <?php if ($block->getLayer()->getState()->getFilters()) : ?>
            <div class="block-actions filter-actions">
                <a href="<?= $block->getClearUrl() ?>" class="action clear filter-clear"><span><?= __('Clear All') ?></span></a>
            </div>
        <?php endif; ?>
        <?php
        $wrapOptions = false;
        foreach ($block->getFilters() as $filter) :
            /** @var \Magento\Catalog\Model\Layer\Filter\AbstractFilter $filter */
            if (! $filter->getItemsCount()) {
                continue;
            }
            ?>
            <?php if (!$wrapOptions) : ?>
                <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= __('Shopping Options') ?></strong>
                <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                    <?php  $wrapOptions = true ?>
            <?php endif ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title">
                            <?= __($filter->getName()) ?> <?php if ($filter->getData('attribute_model')) :
                                ?><?= $helper->getTitleHintHtml($filter->getAttributeModel()->getAttributeId()); ?><?php
                            endif; ?>
                        </div>
                        <div data-role="content" class="filter-options-content"><?= $block->getChildBlock('renderer')->render($filter) ?></div>
                    </div>
        <?php endforeach; ?>
        <?php if ($wrapOptions) : ?>
                </div>
        <?php else : ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $('#layered-filter-block').addClass('filter-no-options');
                });
            </script>
        <?php endif; ?>
    </div>
</div>
